services:
  - type: web
    name: ftcscout-22351
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: VIEW_PASSWORD
        sync: false
      - key: DEV_PASSWORD
        sync: false
